# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9de79b24978f1a34647f13e2025a10d1817b4ad664508b4af595476a62093f6abc2db80628f92c3ff1ac66c704d22bfa52599f280703b94387d9880ccf4714bf

test:
  secret_key_base: fe98e55cb7d5c9f591b4da1fc34cf6a72ead3ee0755970e2ef373659825a8c2b4559a978fdc610e4e48db13d375331f7720ab3c3f50f55d9b4b9e0cfdf074583

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
